-- PNRR3 Basilicata V4
-- Registrazione tramite OTP e moderazione dei nuovi vincitori.
-- Eseguire dopo le migrazioni V2/V3 già installate.

begin;

create table if not exists public.candidate_registration_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  classe text not null check (classe in ('AAAA','ADAA','EEEE','ADEE')),
  posizione integer not null check (posizione > 0),
  punteggio numeric(7,2) not null check (punteggio >= 0),
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

create unique index if not exists candidate_registration_requests_user_unique
  on public.candidate_registration_requests(user_id);

alter table public.candidate_registration_requests enable row level security;
revoke all on table public.candidate_registration_requests from anon, authenticated;

create or replace function public.registration_tuple_exists(
  p_classe text,
  p_posizione integer,
  p_punteggio numeric,
  p_exclude_candidate_id bigint default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.candidati c
    cross join lateral jsonb_to_recordset(c.candidature) as j(
      classe text,
      posizione integer,
      punteggio numeric
    )
    where (p_exclude_candidate_id is null or c.id <> p_exclude_candidate_id)
      and j.classe = p_classe
      and j.posizione = p_posizione
      and round(j.punteggio,2) = round(p_punteggio,2)
  );
$$;

create or replace function public.submit_candidate_registration_request(
  p_classe text,
  p_posizione integer,
  p_punteggio numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_email text;
  current_request public.candidate_registration_requests%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Accesso richiesto';
  end if;

  if exists(select 1 from public.candidati where user_id=auth.uid()) then
    raise exception 'Questo account possiede già un record';
  end if;

  if p_classe not in ('AAAA','ADAA','EEEE','ADEE')
     or p_posizione is null or p_posizione < 1
     or p_punteggio is null or p_punteggio < 0 then
    raise exception 'Dati della graduatoria non validi';
  end if;

  if public.registration_tuple_exists(
    p_classe,
    p_posizione,
    round(p_punteggio,2),
    null
  ) then
    return jsonb_build_object(
      'result','existing_record',
      'message','Esiste già un record con la stessa classe, posizione e punteggio'
    );
  end if;

  select email::text into current_email
  from auth.users
  where id=auth.uid();

  select * into current_request
  from public.candidate_registration_requests
  where user_id=auth.uid();

  if current_request.id is not null and current_request.status='approved' then
    return jsonb_build_object('result','approved');
  end if;

  insert into public.candidate_registration_requests(
    user_id,email,classe,posizione,punteggio,status,
    admin_note,created_at,reviewed_at,reviewed_by
  )
  values(
    auth.uid(),current_email,p_classe,p_posizione,round(p_punteggio,2),
    'pending',null,now(),null,null
  )
  on conflict(user_id) do update set
    email=excluded.email,
    classe=excluded.classe,
    posizione=excluded.posizione,
    punteggio=excluded.punteggio,
    status='pending',
    admin_note=null,
    created_at=now(),
    reviewed_at=null,
    reviewed_by=null;

  return jsonb_build_object('result','pending');
end;
$$;

create or replace function public.get_my_registration_request()
returns table(
  id bigint,
  classe text,
  posizione integer,
  punteggio numeric,
  status text,
  admin_note text,
  created_at timestamptz,
  reviewed_at timestamptz
)
language sql
security definer
stable
set search_path = public
as $$
  select
    r.id::bigint,
    r.classe::text,
    r.posizione::integer,
    r.punteggio::numeric,
    r.status::text,
    r.admin_note::text,
    r.created_at::timestamptz,
    r.reviewed_at::timestamptz
  from public.candidate_registration_requests r
  where r.user_id=auth.uid()
  limit 1;
$$;

create or replace function public.admin_registration_counts()
returns table(
  pending_count bigint,
  approved_count bigint,
  rejected_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  return query
  select
    count(*) filter(where status='pending')::bigint,
    count(*) filter(where status='approved')::bigint,
    count(*) filter(where status='rejected')::bigint
  from public.candidate_registration_requests;
end;
$$;

create or replace function public.admin_list_registration_requests(
  p_status text default 'pending'
)
returns table(
  id bigint,
  user_id uuid,
  email text,
  classe text,
  posizione integer,
  punteggio numeric,
  status text,
  admin_note text,
  existing_matches bigint,
  created_at timestamptz,
  reviewed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  return query
  select
    r.id::bigint,
    r.user_id::uuid,
    r.email::text,
    r.classe::text,
    r.posizione::integer,
    r.punteggio::numeric,
    r.status::text,
    r.admin_note::text,
    (
      select count(*)::bigint
      from public.candidati c
      cross join lateral jsonb_to_recordset(c.candidature) as j(
        classe text,
        posizione integer,
        punteggio numeric
      )
      where j.classe=r.classe
        and j.posizione=r.posizione
        and round(j.punteggio,2)=round(r.punteggio,2)
    )::bigint,
    r.created_at::timestamptz,
    r.reviewed_at::timestamptz
  from public.candidate_registration_requests r
  where p_status='all' or r.status=p_status
  order by
    case when r.status='pending' then 0 else 1 end,
    r.created_at desc;
end;
$$;

create or replace function public.admin_approve_registration_request(
  p_request_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.candidate_registration_requests%rowtype;
begin
  perform public.require_admin();

  select * into request_row
  from public.candidate_registration_requests
  where id=p_request_id
  for update;

  if request_row.id is null then
    raise exception 'Richiesta non trovata';
  end if;

  if request_row.status <> 'pending' then
    raise exception 'La richiesta non è più in attesa';
  end if;

  if exists(select 1 from public.candidati where user_id=request_row.user_id) then
    raise exception 'L’utente possiede già un record';
  end if;

  if public.registration_tuple_exists(
    request_row.classe,
    request_row.posizione,
    request_row.punteggio,
    null
  ) then
    raise exception 'Esiste già un record con la stessa classe, posizione e punteggio: usa la procedura di rivendicazione';
  end if;

  update public.candidate_registration_requests
  set status='approved',
      admin_note='Iscrizione approvata.',
      reviewed_at=now(),
      reviewed_by=auth.uid()
  where id=p_request_id;

  return true;
end;
$$;

create or replace function public.admin_reject_registration_request(
  p_request_id bigint,
  p_admin_note text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  update public.candidate_registration_requests
  set status='rejected',
      admin_note=coalesce(nullif(trim(p_admin_note),''),'Richiesta non approvata.'),
      reviewed_at=now(),
      reviewed_by=auth.uid()
  where id=p_request_id
    and status='pending';

  return found;
end;
$$;

-- Sostituisce l'upsert V2: gli utenti con un record continuano a modificarlo;
-- un nuovo record può essere creato soltanto dopo l'approvazione.
create or replace function public.upsert_my_candidatura_v2(
  p_candidature jsonb,
  p_preferenze_scuole jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id bigint;
  approved_request public.candidate_registration_requests%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Accesso richiesto';
  end if;

  if not public.validate_school_preferences(
    p_candidature,
    p_preferenze_scuole
  ) then
    raise exception 'Dati o preferenze scolastiche non validi';
  end if;

  select id into target_id
  from public.candidati
  where user_id=auth.uid();

  if target_id is null then
    select * into approved_request
    from public.candidate_registration_requests
    where user_id=auth.uid()
      and status='approved';

    if approved_request.id is null then
      raise exception 'La nuova iscrizione deve essere approvata da un amministratore';
    end if;

    if not exists(
      select 1
      from jsonb_to_recordset(p_candidature) as j(
        classe text,
        posizione integer,
        punteggio numeric
      )
      where j.classe=approved_request.classe
        and j.posizione=approved_request.posizione
        and round(j.punteggio,2)=round(approved_request.punteggio,2)
    ) then
      raise exception 'I dati iniziali non corrispondono alla richiesta approvata';
    end if;

    if public.registration_tuple_exists(
      approved_request.classe,
      approved_request.posizione,
      approved_request.punteggio,
      null
    ) then
      raise exception 'Nel frattempo è stato creato un record compatibile: richiedine la rivendicazione';
    end if;

    insert into public.candidati(
      candidature,
      provincia_1,
      provincia_2,
      comuni,
      user_id,
      preferenze_scuole,
      updated_at
    )
    values(
      p_candidature,
      'Potenza',
      null,
      array['Preferenze scolastiche']::text[],
      auth.uid(),
      p_preferenze_scuole,
      now()
    )
    returning id into target_id;
  else
    update public.candidati
    set candidature=p_candidature,
        preferenze_scuole=p_preferenze_scuole,
        updated_at=now()
    where id=target_id;
  end if;

  return target_id;
end;
$$;

revoke all on function public.registration_tuple_exists(text,integer,numeric,bigint) from public;
revoke all on function public.submit_candidate_registration_request(text,integer,numeric) from public;
revoke all on function public.get_my_registration_request() from public;
revoke all on function public.admin_registration_counts() from public;
revoke all on function public.admin_list_registration_requests(text) from public;
revoke all on function public.admin_approve_registration_request(bigint) from public;
revoke all on function public.admin_reject_registration_request(bigint,text) from public;

grant execute on function public.submit_candidate_registration_request(text,integer,numeric) to authenticated;
grant execute on function public.get_my_registration_request() to authenticated;
grant execute on function public.admin_registration_counts() to authenticated;
grant execute on function public.admin_list_registration_requests(text) to authenticated;
grant execute on function public.admin_approve_registration_request(bigint) to authenticated;
grant execute on function public.admin_reject_registration_request(bigint,text) to authenticated;

notify pgrst,'reload schema';

commit;
