-- PNRR3 Basilicata
-- Richieste anonime per associare un codice di modifica alle vecchie compilazioni.
-- Eseguire dopo migration_edit_codes_dashboard.sql.

begin;

create table if not exists public.candidati_legacy_claims (
  id bigint generated by default as identity primary key,
  request_hash text not null,
  classe text not null
    check (classe in ('AAAA', 'ADAA', 'EEEE', 'ADEE')),
  posizione integer not null
    check (posizione > 0),
  punteggio numeric(7,2) not null
    check (punteggio >= 0),
  primo_comune text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  candidate_id bigint
    references public.candidati(id)
    on delete set null,
  edit_code text,
  admin_note text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.candidati_legacy_claims enable row level security;
revoke all on table public.candidati_legacy_claims from anon, authenticated;

create or replace function public.submit_legacy_claim_request(
  p_request_code text,
  p_classe text,
  p_posizione integer,
  p_punteggio numeric,
  p_primo_comune text
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_id bigint;
begin
  if p_request_code !~ '^CLAIM-[A-Z0-9]{4}-[A-Z0-9]{4}$' then
    raise exception 'Codice richiesta non valido';
  end if;

  if p_classe not in ('AAAA', 'ADAA', 'EEEE', 'ADEE') then
    raise exception 'Classe non valida';
  end if;

  if p_posizione < 1 or p_punteggio < 0 or nullif(trim(p_primo_comune), '') is null then
    raise exception 'Dati richiesta non validi';
  end if;

  insert into public.candidati_legacy_claims (
    request_hash,
    classe,
    posizione,
    punteggio,
    primo_comune
  )
  values (
    extensions.crypt(p_request_code, extensions.gen_salt('bf', 10)),
    p_classe,
    p_posizione,
    p_punteggio,
    trim(p_primo_comune)
  )
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.check_legacy_claim_request(
  p_request_code text
)
returns table (
  status text,
  edit_code text,
  admin_note text
)
language sql
security definer
set search_path = public, extensions
as $$
  select
    c.status,
    c.edit_code,
    c.admin_note
  from public.candidati_legacy_claims c
  where extensions.crypt(p_request_code, c.request_hash) = c.request_hash
  order by c.created_at desc
  limit 1;
$$;

create or replace function public.approve_legacy_claim_request(
  p_request_id bigint,
  p_candidate_id bigint
)
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  generated_code text;
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  random_bytes bytea;
  token text := '';
  i integer;
begin
  if not exists (
    select 1
    from public.candidati_legacy_claims
    where id = p_request_id
      and status = 'pending'
  ) then
    raise exception 'Richiesta non trovata o già esaminata';
  end if;

  if not exists (
    select 1
    from public.candidati
    where id = p_candidate_id
  ) then
    raise exception 'Record candidato non trovato';
  end if;

  if exists (
    select 1
    from public.candidati_edit_tokens
    where candidate_id = p_candidate_id
  ) then
    raise exception 'Questo record possiede già un codice di modifica';
  end if;

  random_bytes := extensions.gen_random_bytes(8);

  for i in 0..7 loop
    token := token || substr(
      alphabet,
      (get_byte(random_bytes, i) % length(alphabet)) + 1,
      1
    );
  end loop;

  generated_code := 'PNRR3-' || substr(token, 1, 4) || '-' || substr(token, 5, 4);

  insert into public.candidati_edit_tokens (
    candidate_id,
    token_hash
  )
  values (
    p_candidate_id,
    extensions.crypt(generated_code, extensions.gen_salt('bf', 10))
  );

  update public.candidati_legacy_claims
  set
    status = 'approved',
    candidate_id = p_candidate_id,
    edit_code = generated_code,
    reviewed_at = now()
  where id = p_request_id;

  return generated_code;
end;
$$;

create or replace function public.reject_legacy_claim_request(
  p_request_id bigint,
  p_admin_note text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.candidati_legacy_claims
  set
    status = 'rejected',
    admin_note = nullif(trim(p_admin_note), ''),
    reviewed_at = now()
  where id = p_request_id
    and status = 'pending';

  return found;
end;
$$;

revoke all on function public.submit_legacy_claim_request(text, text, integer, numeric, text) from public;
revoke all on function public.check_legacy_claim_request(text) from public;
revoke all on function public.approve_legacy_claim_request(bigint, bigint) from public;
revoke all on function public.reject_legacy_claim_request(bigint, text) from public;

grant execute on function public.submit_legacy_claim_request(text, text, integer, numeric, text)
  to anon, authenticated;

grant execute on function public.check_legacy_claim_request(text)
  to anon, authenticated;

-- Le funzioni di approvazione e rifiuto restano disponibili soltanto
-- all'amministratore tramite SQL Editor.

commit;
