-- PNRR3 Basilicata V4.12
-- Pagina amministrativa Utenti, messaggi interni e supporto email.
-- Eseguire dopo la migrazione V4.11.

begin;

create table if not exists public.user_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null check (char_length(subject) between 1 and 160),
  body text not null check (char_length(body) between 1 and 5000),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  read_at timestamptz,
  email_requested boolean not null default false,
  email_status text
);

create index if not exists user_messages_user_created_idx
  on public.user_messages(user_id,created_at desc);

alter table public.user_messages enable row level security;
revoke all on table public.user_messages from anon,authenticated;

create or replace function public.admin_send_user_message(
  p_user_id uuid,
  p_subject text,
  p_body text,
  p_email_requested boolean default false
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  new_id bigint;
begin
  perform public.require_admin();

  if not exists(select 1 from auth.users where id=p_user_id) then
    raise exception 'Utente non trovato';
  end if;

  if nullif(trim(coalesce(p_subject,'')),'') is null
     or char_length(trim(p_subject))>160 then
    raise exception 'Oggetto non valido';
  end if;

  if nullif(trim(coalesce(p_body,'')),'') is null
     or char_length(trim(p_body))>5000 then
    raise exception 'Messaggio non valido';
  end if;

  insert into public.user_messages(
    user_id,subject,body,created_by,email_requested,email_status
  )
  values(
    p_user_id,
    trim(p_subject),
    trim(p_body),
    auth.uid(),
    coalesce(p_email_requested,false),
    case when coalesce(p_email_requested,false) then 'pending' else null end
  )
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.admin_list_user_messages(
  p_user_id uuid
)
returns table(
  id bigint,
  subject text,
  body text,
  created_at timestamptz,
  read_at timestamptz,
  email_status text
)
language plpgsql
security definer
set search_path=public
as $$
begin
  perform public.require_admin();

  return query
  select
    m.id::bigint,
    m.subject::text,
    m.body::text,
    m.created_at::timestamptz,
    m.read_at::timestamptz,
    m.email_status::text
  from public.user_messages m
  where m.user_id=p_user_id
  order by m.created_at desc
  limit 100;
end;
$$;

create or replace function public.get_my_user_messages()
returns table(
  id bigint,
  subject text,
  body text,
  created_at timestamptz,
  read_at timestamptz
)
language sql
stable
security definer
set search_path=public
as $$
  select
    m.id::bigint,
    m.subject::text,
    m.body::text,
    m.created_at::timestamptz,
    m.read_at::timestamptz
  from public.user_messages m
  where m.user_id=auth.uid()
  order by m.created_at desc
  limit 100;
$$;

create or replace function public.mark_my_user_message_read(
  p_message_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then
    raise exception 'Accesso richiesto';
  end if;

  update public.user_messages
  set read_at=coalesce(read_at,now())
  where id=p_message_id
    and user_id=auth.uid();

  return found;
end;
$$;

revoke all on function public.admin_send_user_message(uuid,text,text,boolean) from public;
revoke all on function public.admin_list_user_messages(uuid) from public;
revoke all on function public.get_my_user_messages() from public;
revoke all on function public.mark_my_user_message_read(bigint) from public;

grant execute on function public.admin_send_user_message(uuid,text,text,boolean)
to authenticated;
grant execute on function public.admin_list_user_messages(uuid)
to authenticated;
grant execute on function public.get_my_user_messages()
to authenticated;
grant execute on function public.mark_my_user_message_read(bigint)
to authenticated;

notify pgrst,'reload schema';

commit;
