-- PNRR3 Basilicata V4.14 — Assegnazioni ufficiali
-- Importa primaria e infanzia, abbina i record e congela le preferenze confermate.
begin;

alter table public.candidati
  add column if not exists preferences_locked boolean not null default false;

create table if not exists public.official_assignments (
  id bigint generated by default as identity primary key,
  insegnamento text not null check (insegnamento in ('AAAA','ADAA','EEEE','ADEE')),
  graduatoria text not null,
  posizione integer not null,
  punteggio numeric(8,2) not null,
  esito text not null,
  cognome text,
  nome text,
  provincia_assegnata text not null check (provincia_assegnata in ('Matera','Potenza')),
  codice_scuola text not null,
  denominazione_scuola text not null,
  nomina_coe boolean not null default false,
  fonte text,
  candidate_id bigint references public.candidati(id) on delete set null,
  match_status text not null default 'unmatched'
    check (match_status in ('unmatched','automatic','ambiguous','confirmed','manual')),
  confirmed_at timestamptz,
  confirmed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(insegnamento,graduatoria,posizione,punteggio,codice_scuola)
);

alter table public.official_assignments enable row level security;
revoke all on table public.official_assignments from anon,authenticated;

insert into public.official_assignments(
  insegnamento,graduatoria,posizione,punteggio,esito,cognome,nome,
  provincia_assegnata,codice_scuola,denominazione_scuola,nomina_coe,fonte
)
values
('ADEE','GM26',3,226.0,'Vincitore','Viceconti','Donatella','Potenza','PZEE828015','Primaria - I.C. Rotonda',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',4,225.5,'Vincitore','Devito','Giuseppina','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',5,225.25,'Vincitore','Perillo','Angela','Matera','MTEE823015','Don L. Palazzo-Montescaglioso',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',10,217.0,'Vincitore','Di Benedetto','Elisabetta','Matera','MTEE83401G','"Isabella Morra"-Valsinni',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',11,215.0,'Vincitore','Siggillino','Vittoria','Matera','MTEE808013','S.G.Bosco - Grassano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',13,213.0,'Vincitore','Negro','Antonella Annamaria','Matera','MTEE81801N','F.D''Onofrio-Ic Ferrandina',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',15,209.5,'Vincitore','Cancellara','Daniela','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',18,208.0,'Vincitore','Contini','Rosanna','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',20,207.0,'Vincitore','Terranova','Marisa','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',21,205.75,'Vincitore','Rondinone','Francesco','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',28,198.25,'Vincitore','Fortunato','Carmen Valentina','Potenza','PZEE864029','Primaria Ada Negri-Muro Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('ADEE','GM26',31,195.0,'Vincitore','Vespoli','Rosaria','Potenza','PZEE864029','Primaria Ada Negri-Muro Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',1,240.0,'Vincitore','Giampietro','Raffaele','Matera','MTEE808013','S.G.Bosco - Grassano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',2,238.0,'Vincitore','Longo','Piercarmine','Matera','MTEE81701T','Largo Europa-Nova Siri',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',3,237.0,'Vincitore','Silletti','Maria Antonietta','Matera','MTEE81701T','Largo Europa-Nova Siri',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',4,236.0,'Vincitore','Sirago','Cosima Damiana','Matera','MTEE83201X','Giovanni Paolo Ii-Policoro 2',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',5,234.0,'Vincitore','Fiore','Angela','Matera','MTEE81701T','Largo Europa-Nova Siri',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',6,233.75,'Vincitore','De Palo','Francesca','Matera','MTCT70500A','CTP IRSINA',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',7,232.75,'Vincitore','Armenante','Francesca','Potenza','PZEE879012','Poggio Tre Galli-Sinisgalli Pz',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',8,232.0,'Vincitore','De Carlo','Donatella','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',10,231.0,'Vincitore','Galtieri','Ylenia','Matera','MTEE83401G','"Isabella Morra"-Valsinni',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',11,230.75,'Vincitore','Segreto','Anna','Potenza','PZEE879012','Poggio Tre Galli-Sinisgalli Pz',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',14,228.75,'Vincitore','Petta','Simone','Matera','MTEE83401G','"Isabella Morra"-Valsinni',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',15,227.0,'Vincitore','Natale','Mara','Potenza','PZEE84102L','Primaria "F. S. Nitti"-Melfi',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',16,227.0,'Vincitore','Adesso','Francesca','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',18,226.0,'Vincitore','D''Agostino','Michele','Potenza','PZCT71200A','CPIA PZ-SEDE ASSOCIATA LAVELLO',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',19,226.0,'Vincitore','Cozzi','Anna','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',20,226.0,'Vincitore','Cozzi','Fabiana Domenica','Potenza','PZEE828015','Primaria - I.C. Rotonda',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',21,225.25,'Vincitore','Dambrosio','Serena','Matera','MTEE83401G','"Isabella Morra"-Valsinni',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',23,224.75,'Vincitore','Spada','Sara','Matera','MTEE83401G','"Isabella Morra"-Valsinni',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',24,224.25,'Vincitore','Di Matteo','Giorgia','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',25,224.0,'Vincitore','Paternoster','Federica','Matera','MTEE83401G','"Isabella Morra"-Valsinni',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',26,224.0,'Vincitore','Provenzale','Giulia','Potenza','PZEE82001E','P.F.Grimaldi - Ic Oppido Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',27,223.0,'Vincitore','Di Lecce','Bruna','Matera','MTEE83401G','"Isabella Morra"-Valsinni',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',28,222.75,'Vincitore','Lancellotti','Ilenia','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',30,222.0,'Vincitore','Colia','Carola','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',32,221.75,'Vincitore','Togni','Ivana','Potenza','PZEE82001E','P.F.Grimaldi - Ic Oppido Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',33,221.0,'Vincitore','Bochicchio','Luciana Annarita','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',34,220.5,'Vincitore','Acerenza','Anna Lucia','Potenza','PZEE85901R','Pignola-Capoluogo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',36,220.0,'Vincitore','Loquercio','Anna Lisa','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',37,219.0,'Vincitore','Alvarez','Noemi','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',39,218.0,'Vincitore','Schettini','Silvia','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',40,217.75,'Vincitore','Agneta','Vito','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',41,217.25,'Vincitore','Cerrone','Valentina Maria','Potenza','PZEE86201L','Primaria - I.C. Picerno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',44,216.25,'Vincitore','Innella','Luca','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',45,215.25,'Vincitore','Laguardia','Paola Anna','Potenza','PZEE82601D','Villa D'' Agri - Marsico Vetere',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',46,215.25,'Vincitore','Alagia','Alessia','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',47,215.0,'Vincitore','Mecca','Chiara','Potenza','PZEE87001G','Morlino-Ic S.F. Avigliano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',48,215.0,'Vincitore','Giannone','Serena','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',51,214.75,'Vincitore','Campiglia','Giada Nunziella','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',52,214.0,'Vincitore','Verrico','Domenica','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',56,213.25,'Vincitore','Catalano','Martina Fiorella','Potenza','PZEE87001G','Morlino-Ic S.F. Avigliano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',57,213.25,'Vincitore','Genovese','Miriana','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',58,213.0,'Vincitore','Acucella','Roberta','Potenza','PZEE84102L','Primaria "F. S. Nitti"-Melfi',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',59,212.75,'Vincitore','Di Matteo','Francesca','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',61,212.25,'Vincitore','Guglielmi','Alessia','Potenza','PZEE86201L','Primaria - I.C. Picerno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',62,212.0,'Vincitore','Digirolamo','Angelica','Potenza','PZEE82001E','P.F.Grimaldi - Ic Oppido Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',63,211.5,'Vincitore','Lettieri','Michela','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',64,211.25,'Vincitore','Pierro','Rosa','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',65,211.25,'Vincitore','Pascale','Raffaella Pia','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',67,210.0,'Vincitore','Viggiano','Paola','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',69,209.75,'Vincitore','Bruscella','Serena','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',70,209.5,'Vincitore','Sisto','Sonia','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',71,209.25,'Vincitore','Cappiello','Lorenza','Potenza','PZEE84102L','Primaria "F. S. Nitti"-Melfi',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',71,208.5,'Vincitore','Marcogiuseppe','Fiorella','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',73,207.75,'Vincitore','Roberti','Valeria','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',74,207.5,'Vincitore','Agatiello','Mariangela','Potenza','PZEE87001G','Morlino-Ic S.F. Avigliano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',75,207.0,'Vincitore','Pepe','Annunziata','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',76,206.75,'Vincitore','Prinzi','Loredana','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',77,206.75,'Vincitore','Uricchio','Domenica','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',78,206.0,'Vincitore','Verdevalle','Gloria','Potenza','PZEE86201L','Primaria - I.C. Picerno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',79,206.0,'Vincitore','Lopardo','Donatella','Potenza','PZEE83301L','Primaria - I.C. Marsico Nuovo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',80,206.0,'Vincitore','Matturro','Sara','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',81,206.0,'Vincitore','Puzio','Carmen','Potenza','PZEE83801Q','Primaria - I.C. Viggiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',82,205.25,'Vincitore','Orlando','Stefania','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',83,205.25,'Vincitore','Telesca','Giovanna','Potenza','PZEE84102L','Primaria "F. S. Nitti"-Melfi',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',85,205.0,'Vincitore','Iacovuzzi','Martina','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',86,204.75,'Vincitore','Regina','Antonella','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',87,204.25,'Vincitore','Dicosmo','Teresa','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',88,204.25,'Vincitore','Mormando','Chiara','Potenza','PZEE88503B','I.C. Senise "S.Pietro"',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',91,204.0,'Vincitore','Pintrijel','Angela Maria','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',92,204.0,'Vincitore','Caso','Pierangela','Potenza','PZEE83801Q','Primaria - I.C. Viggiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',93,204.0,'Vincitore','Marolda','Maria Pompea','Potenza','PZEE864029','Primaria Ada Negri-Muro Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',94,203.75,'Vincitore','De Luca','Pasqualina','Potenza','PZEE83301L','Primaria - I.C. Marsico Nuovo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',95,202.25,'Vincitore','Buono','Maria Giovanna','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',96,201.75,'Vincitore','Scatamacchio','Giuseppina','Potenza','PZEE87001G','Morlino-Ic S.F. Avigliano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',97,201.25,'Vincitore','Camardo','Domenico','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',99,201.25,'Vincitore','Crescente','Giuseppina','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',100,201.0,'Vincitore','Fabozzi','Tiziana','Potenza','PZEE82601D','Villa D'' Agri - Marsico Vetere',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',103,200.5,'Vincitore','D''Apice','Cinzia','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',104,200.25,'Vincitore','Cataldo','Eleonora','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',105,200.25,'Vincitore','Mitidieri','Emilia Anna','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',106,200.0,'Vincitore','Ferro','Lucia','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',107,199.75,'Vincitore','Gaito','Oreste','Potenza','PZEE82601D','Villa D'' Agri - Marsico Vetere',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',108,199.75,'Vincitore','Fasano','Feliciana','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',109,199.5,'Vincitore','Lopomo','Rosa','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',110,199.25,'Vincitore','Pietropinto','Elisabetta','Potenza','PZEE89501X','Primaria T.M. Preziuso',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',111,199.25,'Vincitore','Soldovieri','Luisa','Potenza','PZEE864029','Primaria Ada Negri-Muro Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',112,199.0,'Vincitore','Salatino','Nicolina','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',113,198.75,'Vincitore','D''Alessandro','Imma','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',114,198.75,'Vincitore','Rosano','Roberta','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',115,198.5,'Vincitore','Santarsiero','Marialuisa','Potenza','PZEE87001G','Morlino-Ic S.F. Avigliano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',116,197.25,'Vincitore','Laviola','Laura','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',118,196.25,'Vincitore','Targise','Maria','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',119,195.5,'Vincitore','Catarinella','Marta','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',120,195.25,'Vincitore','Sarli','Margherita','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',121,195.25,'Vincitore','Giacomino','Francesca','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',122,194.0,'Vincitore','Iacobellis','Antonella','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',123,193.0,'Vincitore','Panzardi','Mirella','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',124,193.0,'Vincitore','Russo','Noemi','Potenza','PZEE864029','Primaria Ada Negri-Muro Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',125,192.75,'Vincitore','Di Pede','Carmen','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',126,192.5,'Vincitore','Pascuccio','Giovanna','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',127,192.25,'Vincitore','Pastore','Cinzia','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',128,191.5,'Vincitore','Mascolo','Mariangela','Potenza','PZEE815013','Primaria I.C. Rapolla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',129,191.5,'Vincitore','Vitale','Raffaella','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',130,191.25,'Vincitore','Francione','Alessia','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',132,190.75,'Vincitore','Papagni','Giuseppe','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',133,190.25,'Vincitore','Di Marzio','Annamaria','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',134,190.25,'Vincitore','Bellisario','Vanessa','Potenza','PZEE815013','Primaria I.C. Rapolla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',135,190.25,'Vincitore','Cosentino','Antonella','Potenza','PZEE84102L','Primaria "F. S. Nitti"-Melfi',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',136,189.75,'Vincitore','De Palo','Palmina','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',137,187.0,'Vincitore','Di Tolve','Annita','Potenza','PZEE815013','Primaria I.C. Rapolla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',138,186.75,'Vincitore','Notarfrancesco','Antonella','Potenza','PZEE83801Q','Primaria - I.C. Viggiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',139,186.75,'Vincitore','Cassino','Chiara Cristel','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',140,185.75,'Vincitore','Di Lecce','Lidia','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',141,185.0,'Vincitore','Andriulli','Gloria','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',142,184.75,'Vincitore','Briglia','Teresa','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',143,184.75,'Vincitore','Rosato','Federica','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',144,184.5,'Vincitore','Laurino','Mariantonietta','Potenza','PZEE864029','Primaria Ada Negri-Muro Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',145,183.5,'Vincitore','Di Marsico','Loredana','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',146,183.25,'Vincitore','Zelano','Alessia','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',147,183.0,'Vincitore','Lamacchia','Carmen','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',148,183.0,'Vincitore','Lo Giudice','Gabriella','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',149,182.5,'Vincitore','Di Pasquale','Daniela','Potenza','PZEE89501X','Primaria T.M. Preziuso',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',150,181.25,'Vincitore','Cassini','Paola','Potenza','PZEE83801Q','Primaria - I.C. Viggiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',151,181.0,'Vincitore','Orofino','Giovanna','Potenza','PZEE878016','A. Ciancia - Ic Francavilla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',152,180.5,'Vincitore','Palermo','Antonella','Potenza','PZEE83801Q','Primaria - I.C. Viggiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',154,180.25,'Vincitore','Vecchi','Giuseppina','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',155,180.0,'Vincitore','Galati','Elisabetta Annunziata','Potenza','PZEE84102L','Primaria "F. S. Nitti"-Melfi',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',157,179.5,'Vincitore','Scarascia','Genoveffa','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',158,178.25,'Vincitore','Sanchirico','Marcella Salvatrice','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',160,178.0,'Vincitore','Carucci','Teresa','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',161,177.75,'Vincitore','D''Onofrio','Maria Carmela','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',162,177.75,'Vincitore','Balducci','Chiara','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',163,177.5,'Vincitore','Abate','Arianna','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',164,177.5,'Vincitore','Conelli','Annunziata','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',165,176.75,'Vincitore','Guarino','Alessia','Potenza','PZEE88503B','I.C. Senise "S.Pietro"',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',166,176.5,'Vincitore','Annecca','Maria Grazia','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',167,176.0,'Vincitore','Scaramuzzi','Giuseppina','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',168,176.0,'Vincitore','De Santis','Margherita','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',169,175.5,'Vincitore','Perlino','Annunziata','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',170,175.0,'Vincitore','Disabato','Natalia','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',171,174.0,'Vincitore','Puzzutiello','Teresa','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',172,174.0,'Vincitore','Magni','Carlo','Potenza','PZEE88503B','I.C. Senise "S.Pietro"',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',173,173.5,'Vincitore','Strazza','Rosanna','Potenza','PZEE815013','Primaria I.C. Rapolla',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',174,173.5,'Vincitore','Pirrone','Elvira','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',176,172.0,'Vincitore','Caprara','Luisa Domenica','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',177,172.0,'Vincitore','Pontillo','Maria Teresa','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',178,171.5,'Vincitore','Di Donato','Cinzia','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',179,171.5,'Vincitore','Ragosa','Annalucia','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',180,170.5,'Vincitore','Rosa','Teresa','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',181,170.5,'Vincitore','Di Stasio','Antonietta','Potenza','PZEE879012','Poggio Tre Galli-Sinisgalli Pz',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',182,170.5,'Vincitore','Ferrara','Anna Irene','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',183,170.0,'Vincitore','De Bonis','Maria Grazia','Potenza','PZEE864029','Primaria Ada Negri-Muro Lucano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',184,169.0,'Vincitore','Mazzei','Michela','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',185,168.5,'Vincitore','Piliero','Antonella','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',186,168.5,'Vincitore','Latorraca','Maria','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',187,167.25,'Vincitore','Rago','Maria','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',188,167.0,'Vincitore','Piscinelli','Mario Tommaso','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',189,165.0,'Vincitore','Farina','Angela','Potenza','PZEE88503B','I.C. Senise "S.Pietro"',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',190,164.25,'Vincitore','Vitale','Margherita','Potenza','PZEE81701P','Scuola Primaria-Satriano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',191,164.0,'Vincitore','Dimase','Angela','Potenza','PZEE88503B','I.C. Senise "S.Pietro"',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',192,164.0,'Vincitore','Moro','Brunella','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',193,163.5,'Vincitore','Sanseverino','Rosanna','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',194,162.25,'Vincitore','Viceconte','Rachele','Potenza','PZEE874031','S.Brancato - Ic S. Arcangelo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',195,158.5,'Vincitore','Adornetto','Cinzia','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',196,158.0,'Vincitore','Venezia','Nunzia','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',197,157.5,'Vincitore','Stante','Esterina','Potenza','PZEE89201C','S.P. "Matteotti" - Ic Lavello',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',198,157.0,'Vincitore','Stabile','Antonella','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',200,156.75,'Vincitore','Botta','Francesca','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',201,155.0,'Vincitore','Di Giacomo','Filomena','Potenza','PZEE88503B','I.C. Senise "S.Pietro"',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',202,155.0,'Vincitore','Zarrillo','Vita','Potenza','PZEE82402V','Primaria - Baragiano',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',203,153.75,'Vincitore','Danzi','Giuseppina','Potenza','PZEE82101A','Primaria - I.C. Laurenzana',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',204,153.0,'Vincitore','Stasio','Gianna','Potenza','PZEE83301L','Primaria - I.C. Marsico Nuovo',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',205,152.5,'Vincitore','Alagia','Emilia','Potenza','PZEE88503B','I.C. Senise "S.Pietro"',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',206,152.25,'Vincitore','Manzo','Cinzia','Potenza','PZEE85501D','Primaria - I.C. Moliterno',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',207,150.0,'Vincitore','Miriello','Paola','Potenza','PZEE84102L','Primaria "F. S. Nitti"-Melfi',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',208,147.0,'Vincitore','Andrisani','Carmela','Potenza','PZEE857015','"Don Bosco" I.C. Palazzo S. G.',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('EEEE','GM26',209,141.0,'Vincitore','Vecchione','Serena','Potenza','PZEE84102L','Primaria "F. S. Nitti"-Melfi',false,'ELENCO-CONVOCATI-PRIMARIA-CONCORSO.pdf'),
('AAAA','GM26',1,240.0,'Vincitore','Novembre','Stefania','Matera','MTAA82600A','SEMERIA-MINOZZI-FESTA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',2,233.0,'Vincitore','Nobile','Federica','Matera','MTAA82300V','I.C. "D.L. PALAZZO" - MONTESCAGLIOSO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',5,228.5,'Vincitore','Mianulli','Brunella','Matera','MTAA82300V','I.C. "D.L. PALAZZO" - MONTESCAGLIOSO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',11,222.75,'Vincitore','Prete','Domenica','Matera','MTAA828002','IC "ENRICO FERMI" - MATERA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',12,222.25,'Vincitore','Silvestri','Maria Paola','Matera','MTAA82600A','SEMERIA-MINOZZI-FESTA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',14,221.25,'Vincitore','Muscio','Martina','Potenza','PZAA88300B','I.C. "BUSCIOLANO" POTENZA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',15,220.25,'Vincitore','Gallo','Tonia','Matera','MTAA834009','I.C. VALSINNI - TURSI',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',18,218.0,'Vincitore','Sileo','Maria Teresa','Matera','MTAA821007','I.C. TRICARICO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',20,217.75,'Vincitore','Ribba','Maria Carmela','Matera','MTAA82600A','SEMERIA-MINOZZI-FESTA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',23,216.0,'Vincitore','Figliuolo','Mariangela','Potenza','PZAA87400L','I.C. "CASTRONUOVO" S. ARCANGELO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',26,213.25,'Vincitore','Incampo','Valeria','Potenza','PZAA88300B','I.C. "BUSCIOLANO" POTENZA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',29,211.75,'Vincitore','Buono','Ilaria','Potenza','PZAA87900Q','I.C. "L. SINISGALLI" POTENZA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',30,211.25,'Vincitore','D''Onofrio','Mariangela Lucia','Potenza','PZAA863006','I.C. TITO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',31,211.25,'Vincitore','Radesca','Francesca','Potenza','PZAA87400L','I.C. "CASTRONUOVO" S. ARCANGELO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',55,198.25,'Vincitore','Lamacchia','Alessia','Potenza','PZAA869005','I.C. GENZANO DI LUCANIA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',60,193.0,'Vincitore','De Blasio','Maria Teresa','Potenza','PZAA81700C','I.C. SATRIANO - BRIENZA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',70,184.25,'Vincitore','Silletti','Alessia','Potenza','PZAA869005','I.C. GENZANO DI LUCANIA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',72,182.25,'Vincitore','Toce','Maria','Potenza','PZAA821004','I.C. "ALFIERI" LAURENZANA-ALBANO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',75,175.25,'Vincitore','Savino','Mariacarmen','Potenza','PZAA81700C','I.C. SATRIANO - BRIENZA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',78,170.0,'Vincitore','Paiano','Tiziana','Potenza','PZAA85700V','I.C. "S.G. BOSCO" PALAZZO S. G.',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',81,165.5,'Vincitore','Ponzio','Valeria','Potenza','PZAA826007','I. OMNICOMPRENSIVO MARSICOVETERE',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',82,164.0,'Vincitore','Langone','Daniela','Potenza','PZAA83300A','I.C. "B. CROCE" MARSICO NUOVO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',86,157.0,'Vincitore','Di Lascio','Ilaria','Potenza','PZAA87800X','I.C. "DON BOSCO" FRANCAVILLA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',88,153.75,'Vincitore','Logiudice','Maria Paola','Potenza','PZAA863006','I.C. TITO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('AAAA','GM26',90,144.0,'Vincitore','Gualtieri','Filomena','Potenza','PZAA87400L','I.C. "CASTRONUOVO" S. ARCANGELO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('ADAA','GM26',1,234.0,'Vincitore','Ambrosini','Gessica','Potenza','PZAA87400L','I.C. "CASTRONUOVO" S. ARCANGELO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('ADAA','GM26',5,209.75,'Vincitore','Marchese','Monica','Potenza','PZAA82400G','I.C. "CARLUCCI" BARAGIANO-BELLA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('ADAA','GM26',9,206.0,'Vincitore','Sanchirico','Rosy','Potenza','PZAA83800D','I.C. "L. DE LORENZO" VIGGIANO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('ADAA','GM26',10,205.25,'Vincitore','Capece','Francesca','Potenza','PZAA82400G','I.C. "CARLUCCI" BARAGIANO-BELLA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('ADAA','GM26-IDO',12,201.0,'Idoneo','Gallicchio','Sara Teresa','Potenza','PZAA855007','IC "G. RACIOPPI" MOLITERNO',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('ADAA','GM26-IDO',13,199.5,'Idoneo','Ferrara','Carmen','Potenza','PZAA82400G','I.C. "CARLUCCI" BARAGIANO-BELLA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf'),
('ADAA','GM26-IDO',14,198.75,'Idoneo','Figliuolo','Mariangela','Potenza','PZAA84000D','I.C. "C. GENNARI" MARATEA',false,'ELENCO-CONVOCATI-INFANZIA-CONCORSO.pdf')
on conflict(insegnamento,graduatoria,posizione,punteggio,codice_scuola)
do update set
  esito=excluded.esito,
  cognome=excluded.cognome,
  nome=excluded.nome,
  provincia_assegnata=excluded.provincia_assegnata,
  denominazione_scuola=excluded.denominazione_scuola,
  nomina_coe=excluded.nomina_coe,
  fonte=excluded.fonte;

create or replace function public.admin_refresh_official_assignment_matches()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  item record;
  ids bigint[];
  matched integer:=0;
  ambiguous integer:=0;
  unmatched integer:=0;
begin
  perform public.require_admin();

  for item in
    select * from public.official_assignments
    where match_status not in ('confirmed','manual')
  loop
    select array_agg(c.id order by c.id)
    into ids
    from public.candidati c
    where exists(
      select 1
      from jsonb_to_recordset(coalesce(c.candidature,'[]'::jsonb)) as x(
        classe text,posizione integer,punteggio numeric
      )
      where x.classe=item.insegnamento
        and x.posizione=item.posizione
        and round(x.punteggio,2)=round(item.punteggio,2)
    );

    if coalesce(cardinality(ids),0)=1 then
      update public.official_assignments
      set candidate_id=ids[1],match_status='automatic'
      where id=item.id;
      matched:=matched+1;
    elsif coalesce(cardinality(ids),0)>1 then
      update public.official_assignments
      set candidate_id=null,match_status='ambiguous'
      where id=item.id;
      ambiguous:=ambiguous+1;
    else
      update public.official_assignments
      set candidate_id=null,match_status='unmatched'
      where id=item.id;
      unmatched:=unmatched+1;
    end if;
  end loop;

  return jsonb_build_object(
    'automatic',matched,'ambiguous',ambiguous,'unmatched',unmatched
  );
end;
$$;

create or replace function public.admin_list_official_assignments(
  p_class text default null,
  p_status text default null,
  p_query text default null
)
returns table(
  assignment_id bigint,
  insegnamento text,
  graduatoria text,
  posizione integer,
  punteggio numeric,
  esito text,
  cognome text,
  nome text,
  provincia_assegnata text,
  codice_scuola text,
  denominazione_scuola text,
  nomina_coe boolean,
  candidate_id bigint,
  match_status text,
  user_email text,
  preference_position integer
)
language plpgsql
security definer
set search_path=public
as $$
begin
  perform public.require_admin();

  return query
  select
    a.id,a.insegnamento,a.graduatoria,a.posizione,a.punteggio,a.esito,
    a.cognome,a.nome,a.provincia_assegnata,a.codice_scuola,
    a.denominazione_scuola,a.nomina_coe,a.candidate_id,a.match_status,
    u.email::text,
    (
      select pref.ordine
      from jsonb_to_recordset(coalesce(c.preferenze_scuole,'[]'::jsonb))
        as pref(classe text,codice_scuola text,ordine integer)
      where pref.classe=a.insegnamento
        and pref.codice_scuola=a.codice_scuola
      order by pref.ordine
      limit 1
    )::integer
  from public.official_assignments a
  left join public.candidati c on c.id=a.candidate_id
  left join auth.users u on u.id=c.user_id
  where (p_class is null or p_class='' or a.insegnamento=p_class)
    and (p_status is null or p_status='' or p_status='all' or a.match_status=p_status)
    and (
      p_query is null or trim(p_query)=''
      or a.cognome ilike '%'||trim(p_query)||'%'
      or a.nome ilike '%'||trim(p_query)||'%'
      or a.codice_scuola ilike '%'||trim(p_query)||'%'
      or a.denominazione_scuola ilike '%'||trim(p_query)||'%'
      or a.posizione::text=trim(p_query)
    )
  order by
    case a.insegnamento when 'AAAA' then 1 when 'ADAA' then 2 when 'EEEE' then 3 else 4 end,
    a.posizione,a.punteggio desc;
end;
$$;

create or replace function public.admin_confirm_official_assignment(
  p_assignment_id bigint,
  p_candidate_id bigint default null
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  target_candidate bigint;
begin
  perform public.require_admin();

  select coalesce(p_candidate_id,candidate_id)
  into target_candidate
  from public.official_assignments
  where id=p_assignment_id;

  if target_candidate is null then
    raise exception 'Seleziona un record da associare';
  end if;

  if not exists(select 1 from public.candidati where id=target_candidate) then
    raise exception 'Record non trovato';
  end if;

  update public.official_assignments
  set candidate_id=target_candidate,
      match_status=case when p_candidate_id is null then 'confirmed' else 'manual' end,
      confirmed_at=now(),
      confirmed_by=auth.uid()
  where id=p_assignment_id;

  update public.candidati
  set preferences_locked=true,
      updated_at=now()
  where id=target_candidate;

  return found;
end;
$$;

create or replace function public.admin_unlink_official_assignment(
  p_assignment_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare old_candidate bigint;
begin
  perform public.require_admin();

  select candidate_id into old_candidate
  from public.official_assignments
  where id=p_assignment_id;

  update public.official_assignments
  set candidate_id=null,match_status='unmatched',
      confirmed_at=null,confirmed_by=null
  where id=p_assignment_id;

  if old_candidate is not null
     and not exists(
       select 1 from public.official_assignments
       where candidate_id=old_candidate
         and match_status in ('confirmed','manual')
     ) then
    update public.candidati
    set preferences_locked=false,updated_at=now()
    where id=old_candidate;
  end if;

  return found;
end;
$$;

create or replace function public.get_my_official_assignments()
returns table(
  assignment_id bigint,
  insegnamento text,
  graduatoria text,
  posizione integer,
  punteggio numeric,
  esito text,
  provincia_assegnata text,
  codice_scuola text,
  denominazione_scuola text,
  nomina_coe boolean,
  preference_position integer,
  preferences_locked boolean
)
language sql
security definer
set search_path=public
as $$
  select
    a.id,a.insegnamento,a.graduatoria,a.posizione,a.punteggio,a.esito,
    a.provincia_assegnata,a.codice_scuola,a.denominazione_scuola,a.nomina_coe,
    (
      select pref.ordine
      from jsonb_to_recordset(coalesce(c.preferenze_scuole,'[]'::jsonb))
        as pref(classe text,codice_scuola text,ordine integer)
      where pref.classe=a.insegnamento
        and pref.codice_scuola=a.codice_scuola
      order by pref.ordine limit 1
    )::integer,
    c.preferences_locked
  from public.official_assignments a
  join public.candidati c on c.id=a.candidate_id
  where c.user_id=auth.uid()
    and a.match_status in ('confirmed','manual')
  order by a.insegnamento;
$$;

revoke all on function public.admin_refresh_official_assignment_matches() from public;
revoke all on function public.admin_list_official_assignments(text,text,text) from public;
revoke all on function public.admin_confirm_official_assignment(bigint,bigint) from public;
revoke all on function public.admin_unlink_official_assignment(bigint) from public;
revoke all on function public.get_my_official_assignments() from public;

grant execute on function public.admin_refresh_official_assignment_matches() to authenticated;
grant execute on function public.admin_list_official_assignments(text,text,text) to authenticated;
grant execute on function public.admin_confirm_official_assignment(bigint,bigint) to authenticated;
grant execute on function public.admin_unlink_official_assignment(bigint) to authenticated;
grant execute on function public.get_my_official_assignments() to authenticated;


create or replace function public.protect_locked_candidate_preferences()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if old.preferences_locked
     and not public.admin_is_current_user()
     and (
       new.candidature is distinct from old.candidature
       or new.preferenze_scuole is distinct from old.preferenze_scuole
       or new.provincia_assegnata is distinct from old.provincia_assegnata
       or new.provincia_1 is distinct from old.provincia_1
       or new.provincia_2 is distinct from old.provincia_2
       or new.comuni is distinct from old.comuni
     ) then
    raise exception 'Le preferenze sono state congelate dopo la conferma dell’assegnazione ufficiale';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_locked_candidate_preferences_trigger
on public.candidati;

create trigger protect_locked_candidate_preferences_trigger
before update on public.candidati
for each row
execute function public.protect_locked_candidate_preferences();

notify pgrst,'reload schema';
commit;
