-- PNRR3 Basilicata V4.9
-- Creazione delle compilazioni dalle rivendicazioni e utenti pre-registrati.
-- Eseguire dopo la migrazione V4.8.

begin;

create table if not exists public.preregistered_candidate_users (
  id bigint generated by default as identity primary key,
  email text not null,
  candidate_id bigint not null unique
    references public.candidati(id) on delete cascade,
  status text not null default 'waiting'
    check (status in ('waiting','activated')),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  activated_at timestamptz,
  activated_user_id uuid references auth.users(id) on delete set null
);

create unique index if not exists preregistered_candidate_users_email_waiting_idx
  on public.preregistered_candidate_users(lower(email))
  where status='waiting';

alter table public.preregistered_candidate_users enable row level security;
revoke all on table public.preregistered_candidate_users from anon,authenticated;

create or replace function public.admin_create_preregistered_candidate(
  p_email text,
  p_classe text,
  p_posizione integer,
  p_punteggio numeric,
  p_preferenze_scuole jsonb,
  p_provincia_1 text,
  p_provincia_2 text,
  p_comuni text[]
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  clean_email text:=lower(trim(coalesce(p_email,'')));
  candidature_data jsonb;
  clean_comuni text[];
  new_candidate_id bigint;
  existing_auth_user uuid;
begin
  perform public.require_admin();

  if clean_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Inserisci un indirizzo email valido';
  end if;

  if exists(
    select 1 from public.preregistered_candidate_users
    where lower(email)=clean_email and status='waiting'
  ) then
    raise exception 'Esiste già una predisposizione in attesa per questa email';
  end if;

  if p_classe not in ('AAAA','ADAA','EEEE','ADEE')
     or p_posizione is null or p_posizione<1
     or p_punteggio is null or p_punteggio<0 then
    raise exception 'Classe, posizione o punteggio non validi';
  end if;

  candidature_data=jsonb_build_array(jsonb_build_object(
    'classe',p_classe,
    'posizione',p_posizione,
    'punteggio',round(p_punteggio,2)
  ));

  if not public.validate_school_preferences(
    candidature_data,p_preferenze_scuole
  ) then
    raise exception 'Preferenze scolastiche non valide';
  end if;

  if exists(
    select 1
    from jsonb_to_recordset(p_preferenze_scuole) pref(
      classe text,codice_scuola text,ordine integer
    )
    where pref.classe<>p_classe
  ) then
    raise exception 'Le scuole devono appartenere alla classe indicata';
  end if;

  if public.registration_tuple_exists(
    p_classe,p_posizione,round(p_punteggio,2),null
  ) then
    raise exception 'Esiste già una compilazione con la stessa classe, posizione e punteggio';
  end if;

  if p_provincia_1 not in ('Potenza','Matera')
     or (
       nullif(trim(coalesce(p_provincia_2,'')),'') is not null
       and p_provincia_2 not in ('Potenza','Matera')
     )
     or nullif(trim(coalesce(p_provincia_2,'')),'')=p_provincia_1 then
    raise exception 'Province non valide';
  end if;

  select array_agg(distinct trim(value))
  into clean_comuni
  from unnest(coalesce(p_comuni,array[]::text[])) value
  where nullif(trim(value),'') is not null;

  if coalesce(cardinality(clean_comuni),0) not between 1 and 20 then
    raise exception 'Dati territoriali non validi';
  end if;

  select id into existing_auth_user
  from auth.users
  where lower(email)=clean_email
  limit 1;

  if existing_auth_user is not null
     and exists(select 1 from public.candidati where user_id=existing_auth_user) then
    raise exception 'L’account associato a questa email possiede già una compilazione';
  end if;

  insert into public.candidati(
    candidature,provincia_1,provincia_2,comuni,user_id,
    preferenze_scuole,updated_at
  )
  values(
    candidature_data,
    p_provincia_1,
    nullif(trim(coalesce(p_provincia_2,'')),''),
    clean_comuni,
    existing_auth_user,
    p_preferenze_scuole,
    now()
  )
  returning id into new_candidate_id;

  insert into public.preregistered_candidate_users(
    email,candidate_id,status,created_by,activated_at,activated_user_id
  )
  values(
    clean_email,
    new_candidate_id,
    case when existing_auth_user is null then 'waiting' else 'activated' end,
    auth.uid(),
    case when existing_auth_user is null then null else now() end,
    existing_auth_user
  );

  return new_candidate_id;
end;
$$;

create or replace function public.admin_create_candidate_from_claim(
  p_request_id bigint,
  p_email text,
  p_classe text,
  p_posizione integer,
  p_punteggio numeric,
  p_preferenze_scuole jsonb,
  p_provincia_1 text,
  p_provincia_2 text,
  p_comuni text[]
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  claim_row public.candidati_legacy_claims%rowtype;
  clean_email text:=lower(trim(coalesce(p_email,'')));
  candidature_data jsonb;
  clean_comuni text[];
  target_user uuid;
  new_candidate_id bigint;
begin
  perform public.require_admin();

  select * into claim_row
  from public.candidati_legacy_claims
  where id=p_request_id
  for update;

  if claim_row.id is null or claim_row.status<>'pending' then
    raise exception 'La richiesta non è più in attesa';
  end if;

  if p_classe<>claim_row.classe
     or p_posizione<>claim_row.posizione
     or round(p_punteggio,2)<>round(claim_row.punteggio,2) then
    raise exception 'I dati non coincidono con la richiesta';
  end if;

  if clean_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Inserisci un indirizzo email valido';
  end if;

  candidature_data=jsonb_build_array(jsonb_build_object(
    'classe',claim_row.classe,
    'posizione',claim_row.posizione,
    'punteggio',round(claim_row.punteggio,2)
  ));

  if not public.validate_school_preferences(
    candidature_data,p_preferenze_scuole
  ) then
    raise exception 'Preferenze scolastiche non valide';
  end if;

  if public.registration_tuple_exists(
    claim_row.classe,claim_row.posizione,claim_row.punteggio,null
  ) then
    raise exception 'Nel frattempo è stata creata una compilazione coincidente: esegui nuovamente la ricerca';
  end if;

  select array_agg(distinct trim(value))
  into clean_comuni
  from unnest(coalesce(p_comuni,array[]::text[])) value
  where nullif(trim(value),'') is not null;

  if coalesce(cardinality(clean_comuni),0) not between 1 and 20 then
    raise exception 'Dati territoriali non validi';
  end if;

  target_user=claim_row.requester_user_id;

  if target_user is null then
    select id into target_user
    from auth.users
    where lower(email)=clean_email
    limit 1;
  end if;

  if target_user is not null
     and exists(select 1 from public.candidati where user_id=target_user) then
    raise exception 'L’account possiede già una compilazione';
  end if;

  insert into public.candidati(
    candidature,provincia_1,provincia_2,comuni,user_id,
    preferenze_scuole,updated_at
  )
  values(
    candidature_data,
    p_provincia_1,
    nullif(trim(coalesce(p_provincia_2,'')),''),
    clean_comuni,
    target_user,
    p_preferenze_scuole,
    now()
  )
  returning id into new_candidate_id;

  if target_user is null then
    insert into public.preregistered_candidate_users(
      email,candidate_id,status,created_by
    )
    values(clean_email,new_candidate_id,'waiting',auth.uid());
  end if;

  update public.candidati_legacy_claims
  set status='approved',
      candidate_id=new_candidate_id,
      admin_note=case
        when target_user is null
          then 'Compilazione creata dall’amministrazione. In attesa del primo accesso con l’email comunicata.'
        else 'Compilazione creata e associata direttamente all’account.'
      end,
      reviewed_at=now()
  where id=p_request_id;

  return new_candidate_id;
end;
$$;

create or replace function public.claim_my_preregistered_candidate()
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  current_email text;
  prereg public.preregistered_candidate_users%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Accesso richiesto';
  end if;

  select lower(email) into current_email
  from auth.users
  where id=auth.uid();

  if current_email is null then
    return null;
  end if;

  select * into prereg
  from public.preregistered_candidate_users
  where lower(email)=current_email
    and status='waiting'
  order by created_at
  limit 1
  for update;

  if prereg.id is null then
    return null;
  end if;

  if exists(
    select 1 from public.candidati
    where user_id=auth.uid() and id<>prereg.candidate_id
  ) then
    raise exception 'Questo account possiede già un’altra compilazione';
  end if;

  update public.candidati
  set user_id=auth.uid(),updated_at=now()
  where id=prereg.candidate_id
    and (user_id is null or user_id=auth.uid());

  if not found then
    raise exception 'La compilazione predisposta è già associata a un altro account';
  end if;

  update public.preregistered_candidate_users
  set status='activated',
      activated_at=now(),
      activated_user_id=auth.uid()
  where id=prereg.id;

  return prereg.candidate_id;
end;
$$;

create or replace function public.admin_list_preregistered_users()
returns table(
  id bigint,
  email text,
  candidate_id bigint,
  status text,
  created_at timestamptz,
  activated_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $$
begin
  perform public.require_admin();

  return query
  select
    p.id::bigint,p.email::text,p.candidate_id::bigint,p.status::text,
    p.created_at::timestamptz,p.activated_at::timestamptz
  from public.preregistered_candidate_users p
  order by
    case when p.status='waiting' then 0 else 1 end,
    p.created_at desc;
end;
$$;

create or replace function public.admin_delete_preregistered_user(
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  prereg public.preregistered_candidate_users%rowtype;
begin
  perform public.require_admin();

  select * into prereg
  from public.preregistered_candidate_users
  where id=p_id
  for update;

  if prereg.id is null then
    return false;
  end if;

  if prereg.status<>'waiting' then
    raise exception 'Non puoi eliminare una predisposizione già attivata';
  end if;

  delete from public.candidati where id=prereg.candidate_id;
  return true;
end;
$$;

revoke all on function public.admin_create_preregistered_candidate(
  text,text,integer,numeric,jsonb,text,text,text[]
) from public;
revoke all on function public.admin_create_candidate_from_claim(
  bigint,text,text,integer,numeric,jsonb,text,text,text[]
) from public;
revoke all on function public.claim_my_preregistered_candidate() from public;
revoke all on function public.admin_list_preregistered_users() from public;
revoke all on function public.admin_delete_preregistered_user(bigint) from public;

grant execute on function public.admin_create_preregistered_candidate(
  text,text,integer,numeric,jsonb,text,text,text[]
) to authenticated;
grant execute on function public.admin_create_candidate_from_claim(
  bigint,text,text,integer,numeric,jsonb,text,text,text[]
) to authenticated;
grant execute on function public.claim_my_preregistered_candidate()
to authenticated;
grant execute on function public.admin_list_preregistered_users()
to authenticated;
grant execute on function public.admin_delete_preregistered_user(bigint)
to authenticated;

notify pgrst,'reload schema';

commit;
