-- PNRR3 Basilicata V4.4
-- Richieste di assistenza manuale per utenti che non riescono ad autenticarsi.
-- Eseguire dopo la migrazione V4.

begin;

create table if not exists public.manual_support_requests (
  id bigint generated by default as identity primary key,
  email text not null,
  contact_email text,
  classe text not null check (classe in ('AAAA','ADAA','EEEE','ADEE')),
  posizione integer not null check (posizione > 0),
  punteggio numeric(7,2) not null check (punteggio >= 0),
  issue text not null check (
    issue in ('google','otp','both','existing_account','other')
  ),
  note text,
  status text not null default 'pending' check (
    status in ('pending','in_progress','resolved','dismissed')
  ),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

create index if not exists manual_support_requests_status_created_idx
  on public.manual_support_requests(status, created_at desc);

create index if not exists manual_support_requests_email_idx
  on public.manual_support_requests(lower(email));

alter table public.manual_support_requests enable row level security;
revoke all on table public.manual_support_requests from anon, authenticated;

create or replace function public.submit_manual_support_request(
  p_email text,
  p_contact_email text,
  p_classe text,
  p_posizione integer,
  p_punteggio numeric,
  p_issue text,
  p_note text default null,
  p_website text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_email text := lower(trim(coalesce(p_email,'')));
  clean_contact text := nullif(lower(trim(coalesce(p_contact_email,''))),'');
  existing_id bigint;
begin
  -- Campo honeypot: risposta neutra senza memorizzare spam automatico.
  if nullif(trim(coalesce(p_website,'')),'') is not null then
    return true;
  end if;

  if clean_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Inserisci un indirizzo email valido';
  end if;

  if clean_contact is not null
     and clean_contact !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Inserisci un indirizzo alternativo valido';
  end if;

  if p_classe not in ('AAAA','ADAA','EEEE','ADEE')
     or p_posizione is null or p_posizione < 1
     or p_punteggio is null or p_punteggio < 0 then
    raise exception 'Controlla classe, posizione e punteggio';
  end if;

  if p_issue not in ('google','otp','both','existing_account','other') then
    raise exception 'Seleziona il problema riscontrato';
  end if;

  if length(coalesce(p_note,'')) > 800 then
    raise exception 'La nota è troppo lunga';
  end if;

  select id into existing_id
  from public.manual_support_requests
  where lower(email)=clean_email
    and status in ('pending','in_progress')
  order by created_at desc
  limit 1;

  if existing_id is not null then
    update public.manual_support_requests
    set contact_email=clean_contact,
        classe=p_classe,
        posizione=p_posizione,
        punteggio=round(p_punteggio,2),
        issue=p_issue,
        note=nullif(trim(coalesce(p_note,'')),''),
        updated_at=now()
    where id=existing_id;
  else
    insert into public.manual_support_requests(
      email,contact_email,classe,posizione,punteggio,issue,note
    )
    values(
      clean_email,
      clean_contact,
      p_classe,
      p_posizione,
      round(p_punteggio,2),
      p_issue,
      nullif(trim(coalesce(p_note,'')),'')
    );
  end if;

  return true;
end;
$$;

create or replace function public.admin_manual_support_counts()
returns table(
  pending_count bigint,
  in_progress_count bigint,
  resolved_count bigint,
  dismissed_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  return query
  select
    count(*) filter(where status='pending')::bigint,
    count(*) filter(where status='in_progress')::bigint,
    count(*) filter(where status='resolved')::bigint,
    count(*) filter(where status='dismissed')::bigint
  from public.manual_support_requests;
end;
$$;

create or replace function public.admin_list_manual_support_requests(
  p_status text default 'pending'
)
returns table(
  id bigint,
  email text,
  contact_email text,
  classe text,
  posizione integer,
  punteggio numeric,
  issue text,
  note text,
  status text,
  admin_note text,
  existing_matches bigint,
  created_at timestamptz,
  updated_at timestamptz,
  reviewed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  return query
  select
    r.id::bigint,
    r.email::text,
    r.contact_email::text,
    r.classe::text,
    r.posizione::integer,
    r.punteggio::numeric,
    r.issue::text,
    r.note::text,
    r.status::text,
    r.admin_note::text,
    (
      select count(*)::bigint
      from public.candidati c
      cross join lateral jsonb_to_recordset(c.candidature) as j(
        classe text,
        posizione integer,
        punteggio numeric
      )
      where j.classe=r.classe
        and j.posizione=r.posizione
        and round(j.punteggio,2)=round(r.punteggio,2)
    )::bigint as existing_matches,
    r.created_at::timestamptz,
    r.updated_at::timestamptz,
    r.reviewed_at::timestamptz
  from public.manual_support_requests r
  where p_status='all' or r.status=p_status
  order by
    case r.status
      when 'pending' then 0
      when 'in_progress' then 1
      when 'resolved' then 2
      else 3
    end,
    r.created_at desc;
end;
$$;

create or replace function public.admin_update_manual_support_request(
  p_request_id bigint,
  p_status text,
  p_admin_note text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.require_admin();

  if p_status not in ('pending','in_progress','resolved','dismissed') then
    raise exception 'Stato non valido';
  end if;

  update public.manual_support_requests
  set status=p_status,
      admin_note=nullif(trim(coalesce(p_admin_note,'')),''),
      updated_at=now(),
      reviewed_at=case
        when p_status in ('resolved','dismissed') then now()
        else reviewed_at
      end,
      reviewed_by=auth.uid()
  where id=p_request_id;

  return found;
end;
$$;

revoke all on function public.submit_manual_support_request(
  text,text,text,integer,numeric,text,text,text
) from public;
revoke all on function public.admin_manual_support_counts() from public;
revoke all on function public.admin_list_manual_support_requests(text) from public;
revoke all on function public.admin_update_manual_support_request(
  bigint,text,text
) from public;

grant execute on function public.submit_manual_support_request(
  text,text,text,integer,numeric,text,text,text
) to anon, authenticated;
grant execute on function public.admin_manual_support_counts() to authenticated;
grant execute on function public.admin_list_manual_support_requests(text) to authenticated;
grant execute on function public.admin_update_manual_support_request(
  bigint,text,text
) to authenticated;

notify pgrst,'reload schema';

commit;
