-- PNRR3 Basilicata V4.13
-- Provincia di assegnazione e messaggi globali.
-- Eseguire dopo la migrazione V4.12.1.

begin;

alter table public.candidati
  add column if not exists provincia_assegnata text;

alter table public.candidati
  drop constraint if exists candidati_provincia_assegnata_check;

alter table public.candidati
  add constraint candidati_provincia_assegnata_check
  check (
    provincia_assegnata is null
    or provincia_assegnata in ('Matera','Potenza')
  );

alter table public.user_messages
  add column if not exists broadcast_id bigint;

create table if not exists public.broadcast_messages (
  id bigint generated by default as identity primary key,
  subject text not null check (char_length(subject) between 1 and 160),
  body text not null check (char_length(body) between 1 and 5000),
  recipient_count integer not null default 0,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create index if not exists user_messages_broadcast_idx
  on public.user_messages(broadcast_id)
  where broadcast_id is not null;

alter table public.broadcast_messages enable row level security;
revoke all on table public.broadcast_messages from anon,authenticated;

drop function if exists public.get_my_candidatura_v2();

create function public.get_my_candidatura_v2()
returns table (
  id bigint,
  candidature jsonb,
  preferenze_scuole jsonb,
  provincia_assegnata text,
  provincia_1 text,
  provincia_2 text,
  comuni text[],
  updated_at timestamptz
)
language sql
security definer
set search_path=public
as $$
  select
    c.id,
    c.candidature,
    c.preferenze_scuole,
    c.provincia_assegnata,
    c.provincia_1,
    c.provincia_2,
    c.comuni,
    c.updated_at
  from public.candidati c
  where c.user_id=auth.uid()
  limit 1;
$$;

drop function if exists public.upsert_my_candidatura_v2(jsonb,jsonb);
drop function if exists public.upsert_my_candidatura_v2(jsonb,jsonb,boolean);
drop function if exists public.upsert_my_candidatura_v2(jsonb,jsonb,text,text[]);

create function public.upsert_my_candidatura_v2(
  p_candidature jsonb,
  p_preferenze_scuole jsonb,
  p_provincia_assegnata text,
  p_comuni text[]
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  target_id bigint;
  approved_request public.candidate_registration_requests%rowtype;
  clean_comuni text[];
  prefs jsonb:=coalesce(p_preferenze_scuole,'[]'::jsonb);
begin
  if auth.uid() is null then
    raise exception 'Accesso richiesto';
  end if;

  if p_provincia_assegnata not in ('Matera','Potenza') then
    raise exception 'Seleziona una provincia di assegnazione valida';
  end if;

  if not public.validate_school_preferences(p_candidature,prefs) then
    raise exception 'Dati o preferenze scolastiche non validi';
  end if;

  select array_agg(distinct trim(value) order by trim(value))
  into clean_comuni
  from unnest(coalesce(p_comuni,array[]::text[])) value
  where nullif(trim(value),'') is not null;

  if coalesce(cardinality(clean_comuni),0) not between 1 and 100 then
    raise exception 'I dati territoriali della provincia assegnata non sono validi';
  end if;

  select id
  into target_id
  from public.candidati
  where user_id=auth.uid()
  for update;

  if target_id is null then
    if jsonb_array_length(prefs)=0 then
      raise exception 'Aggiungi almeno una scuola della provincia assegnata';
    end if;

    select *
    into approved_request
    from public.candidate_registration_requests
    where user_id=auth.uid()
      and status='approved';

    if approved_request.id is null then
      raise exception 'La nuova iscrizione deve essere approvata da un amministratore';
    end if;

    if not exists(
      select 1
      from jsonb_to_recordset(p_candidature) as item(
        classe text,
        posizione integer,
        punteggio numeric
      )
      where item.classe=approved_request.classe
        and item.posizione=approved_request.posizione
        and round(item.punteggio,2)=round(approved_request.punteggio,2)
    ) then
      raise exception 'I dati iniziali non corrispondono alla richiesta approvata';
    end if;

    if public.registration_tuple_exists(
      approved_request.classe,
      approved_request.posizione,
      approved_request.punteggio,
      null
    ) then
      raise exception 'Esiste già un record compatibile: richiedine la rivendicazione';
    end if;

    insert into public.candidati(
      candidature,
      provincia_1,
      provincia_2,
      provincia_assegnata,
      comuni,
      user_id,
      preferenze_scuole,
      updated_at
    )
    values(
      p_candidature,
      p_provincia_assegnata,
      null,
      p_provincia_assegnata,
      clean_comuni,
      auth.uid(),
      prefs,
      now()
    )
    returning id into target_id;
  else
    update public.candidati
    set candidature=p_candidature,
        preferenze_scuole=prefs,
        provincia_assegnata=p_provincia_assegnata,
        provincia_1=p_provincia_assegnata,
        provincia_2=null,
        comuni=clean_comuni,
        updated_at=now()
    where id=target_id;
  end if;

  return target_id;
end;
$$;

create or replace function public.admin_send_broadcast_message(
  p_subject text,
  p_body text
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  new_broadcast_id bigint;
  delivered integer;
begin
  perform public.require_admin();

  if nullif(trim(coalesce(p_subject,'')),'') is null
     or char_length(trim(p_subject))>160 then
    raise exception 'Oggetto non valido';
  end if;

  if nullif(trim(coalesce(p_body,'')),'') is null
     or char_length(trim(p_body))>5000 then
    raise exception 'Messaggio non valido';
  end if;

  insert into public.broadcast_messages(
    subject,body,created_by
  )
  values(
    trim(p_subject),trim(p_body),auth.uid()
  )
  returning id into new_broadcast_id;

  insert into public.user_messages(
    user_id,
    subject,
    body,
    created_by,
    email_requested,
    broadcast_id
  )
  select
    u.id,
    trim(p_subject),
    trim(p_body),
    auth.uid(),
    false,
    new_broadcast_id
  from auth.users u;

  get diagnostics delivered=row_count;

  update public.broadcast_messages
  set recipient_count=delivered
  where id=new_broadcast_id;

  return delivered;
end;
$$;

create or replace function public.admin_list_broadcast_messages()
returns table(
  id bigint,
  subject text,
  body text,
  recipient_count integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $$
begin
  perform public.require_admin();

  return query
  select
    b.id::bigint,
    b.subject::text,
    b.body::text,
    b.recipient_count::integer,
    b.created_at::timestamptz
  from public.broadcast_messages b
  order by b.created_at desc
  limit 50;
end;
$$;

revoke all on function public.get_my_candidatura_v2() from public;
revoke all on function public.upsert_my_candidatura_v2(jsonb,jsonb,text,text[]) from public;
revoke all on function public.admin_send_broadcast_message(text,text) from public;
revoke all on function public.admin_list_broadcast_messages() from public;

grant execute on function public.get_my_candidatura_v2()
to authenticated;
grant execute on function public.upsert_my_candidatura_v2(jsonb,jsonb,text,text[])
to authenticated;
grant execute on function public.admin_send_broadcast_message(text,text)
to authenticated;
grant execute on function public.admin_list_broadcast_messages()
to authenticated;

notify pgrst,'reload schema';

commit;
