create table if not exists public.candidati (
  id bigint generated by default as identity primary key,
  classe_concorso text not null
    check (classe_concorso in ('AAAA', 'ADAA', 'EEEE', 'ADEE')),
  posizione integer not null
    check (posizione > 0),
  punteggio numeric(7,2) not null
    check (punteggio >= 0),
  provincia_1 text not null
    check (provincia_1 in ('Potenza', 'Matera')),
  provincia_2 text
    check (provincia_2 is null or provincia_2 in ('Potenza', 'Matera')),
  comuni text[] not null,
  created_at timestamptz not null default now(),
  constraint comuni_da_1_a_20 check (
    cardinality(comuni) between 1 and 20
  ),
  constraint province_diverse check (
    provincia_2 is null or provincia_2 <> provincia_1
  )
);

alter table public.candidati enable row level security;

drop policy if exists "Lettura pubblica risultati" on public.candidati;
create policy "Lettura pubblica risultati"
on public.candidati
for select
to anon, authenticated
using (true);

drop policy if exists "Inserimento pubblico anonimo" on public.candidati;
create policy "Inserimento pubblico anonimo"
on public.candidati
for insert
to anon, authenticated
with check (
  classe_concorso in ('AAAA', 'ADAA', 'EEEE', 'ADEE')
  and posizione > 0
  and punteggio >= 0
  and provincia_1 in ('Potenza', 'Matera')
  and (provincia_2 is null or provincia_2 in ('Potenza', 'Matera'))
  and (provincia_2 is null or provincia_2 <> provincia_1)
  and cardinality(comuni) between 1 and 20
);

grant usage on schema public to anon, authenticated;
grant select, insert on table public.candidati to anon, authenticated;
grant usage, select on sequence public.candidati_id_seq to anon, authenticated;
